const books = [
    {
        "id":1,
        "bookName":"Feminisimo para principantes",
        "year":2019,
        "editorial":"Penguin Random House",
        "author":"Nuria Varela",
        "image":"https://images-na.ssl-images-amazon.com/images/I/819SKuVK7bL.jpg",
        "genre":"Políticas de igualdad",
    },
    {
        "id":2,
        "bookName":"Feminisimo 4.0 La Cuarta Ola",
        "year":2019,
        "editorial":"Penguin Random House",
        "author":"Nuria Varela",
        "image": "https://images-na.ssl-images-amazon.com/images/I/71ESReSR7SL.jpg",
        "genre": "Políticas de igualdad",
    },
    {
        "id": 3,
        "bookName": "Abrir el melón",
        "year": 2020,
        "editorial": "LIBROS DEL K.O, S.L.L",
        "author": "June Fernandez",
        "image":  "https://cdn.shopify.com/s/files/1/0713/0149/products/Portada_Abrirelmelon_3f76c348-9fdb-4516-8ad5-0dba50a9882b.jpg?v=1602503828",
        "genre": "Medios de comunicación",
    },
    {
        "id": 4,
        "bookName": "Brujas Guerreras Diosas",
        "year": 2020,
        "editorial": "Libros del zorro rojo",
        "author": "Kate Hodges",
        "image":  "https://librosdelzorrorojo.com/wp-content/uploads/2020/10/COVER_Mujeres_WEB.jpg",
        "genre": "Historia",
    },
    {
        "id": 5,
        "bookName": "Las hijas de Lilith",
        "year": 2020,
        "editorial": "Cátedra",
        "author": "Erika Bornay",
        "image":  "https://www.catedra.com/imagenes/libros/grande/9788437641348-las-hijas-de-lilith.jpg",
        "genre": "Cultura",
    },
    {
        "id": 6,
        "bookName": "Mujeres, casas y ciudades",
        "year": 2018,
        "editorial": "dpr Barcelona",
        "author": "Zaida Muxí Martínez",
        "image":  "https://imagessl0.casadellibro.com/a/l/t7/60/9788494752360.jpg",
        "genre": "Cultura",
    },
    {
        "id": 7,
        "bookName": "Caliban i la bruixa, dones, cos i acumulació primitiva",
        "year": 2018,
        "editorial":"Virus",
        "author": "Silvia Federici",
        "image": "https://www.viruseditorial.net/portadas/caliban-i-la-bruixa.png",
        "genre": "Economía",
    },
    {
        "id": 8,
        "bookName": "Las mentiras científicas sobre las mujeres",
        "year": 2017,
        "editorial": "Catarata",
        "author": " Dau García Dauder y Eulalia Pérez Sedeño",
        "image": "https://imagessl6.casadellibro.com/a/l/t7/56/9788490972656.jpg",
        "genre": "Ciencia y tecnología",
    },
]